[project]
name = "paircode"
version = "0.1.0"
description = "A pair of AI devs at your disposal that work on code-related problems."
authors = [
    { name = "Your Name", email = "your@email.com" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-anthropic>=0.3.21",
    "langgraph>=0.6.8",
    "langgraph-swarm>=0.0.14",
    "rich>=14.1.0",
    "typer>=0.19.2",
]

[tool.uv]
package = true

[project.scripts]
paircode = "paircode.cli:app"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["paircode"]
